version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432 (adjust if needed)
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist PostgreSQL data in named volume pgdata

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000
    environment:
      - NODE_ENV=production  # Set Node environment to production
    volumes:
      - .:/app  # Mount local directory to /app in the container
    depends_on:
      - postgres  # Ensure PostgreSQL service is started first

volumes:
  pgdata:  # Define the volume for PostgreSQL data persistence
